<?php

namespace App\Providers;

use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        $this->configureRateLimiting();
        $this->configureModels();
        $this->configureUrls();
    }

    /**
     * Named rate limiters used by routes/api.php via ->middleware('throttle:name').
     */
    protected function configureRateLimiting(): void
    {
        RateLimiter::for('api', function (Request $request) {
            return Limit::perMinute(60)->by($request->user()?->id ?: $request->ip());
        });
    }

    /**
     * Model ergonomics:
     *  - preventLazyLoading in non-prod catches N+1 / missing-relation bugs early
     *  - preventSilentlyDiscardingAttributes blocks mass-assignment of un-fillable keys
     */
    protected function configureModels(): void
    {
        if (! app()->isProduction()) {
            Model::preventLazyLoading();
            Model::preventSilentlyDiscardingAttributes();
        }
    }

    /**
     * In production, force HTTPS for any URL generated by the app (asset URLs,
     * storage URLs, payment callback URLs, etc.).
     */
    protected function configureUrls(): void
    {
        if (app()->isProduction()) {
            URL::forceScheme('https');
        }
    }
}
